# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  schedule:
    - cron: "0 * * * *"
  workflow_dispatch:
  pull_request:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    
    # The type of runner that the job will run on
    runs-on: [ self-hosted, Linux ]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout Repository
        uses: actions/checkout@v2.3.1
      - name: set up node
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - name: Install newman
        run: npm install -g newman newman-reporter-junitfull
      - name: Run POSTMAN collection
        run: |
          mkdir -p testResults
          newman run ./APITests.postman_collection.json \
          -e ./APITest_Dev.postman_environment.json \
          -r junitfull \
          --reporter-junitfull-export testResults/result.xml \
          -n 2 \
      - name: Send message to Slack API
        id: slack
        if: failure() #only send message when test fail
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_CHANNEL: U027XFPFPA8
          SLACK_COLOR: ${{ job.status }} # or a specific color like 'green' or '#ff00ff'
          SLACK_MESSAGE: 'Check out the result https://github.xmedia.ch/Immoscout24/api-tests/actions/runs/${{ github.run_id }}'
          SLACK_TITLE: Contract test failed
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
      - name: Output the run Details
        uses: actions/upload-artifact@v2
        if: always()    # run this step even if previous step failed
        with: 
          name: RunReports
          path: ./testResults
          retention-days: 5
      - name: Publish Test Report
        uses: mikepenz/action-junit-report@v2
        if: always()    # run this step even if previous step failed
        with:
          report_paths: './testResults/result.xml' 
